---
# handlers file for filebeat
- name: Stop default filebeat
  systemd:
    name: filebeat
    state: stopped
    enabled: False
  become: True

- name: Reload systemd configuration
  systemd:
    daemon_reload: True
  become: True

- name: Start filebeat systemd
  systemd:
    name: '{{ fb_service_script }}'
    state: started
    enabled: True
    #daemon-reload: True
  become: True

- name: Start filebeat initd
  service:
    name: '{{ fb_service_script }}'
    # pattern: "{{ path.home }}/bin/filebeat"
    state: restarted
    enabled: True
  become: True
